# Generated by Django 4.2.1 on 2023-05-24 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import near_cars.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearCarsUszip',
            fields=[
                ('zip', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state_id', models.TextField(blank=True, null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
                ('zcta', models.TextField(blank=True, null=True)),
                ('parent_zcta', models.TextField(blank=True, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('density', models.TextField(blank=True, null=True)),
                ('county_fips', models.IntegerField(blank=True, null=True)),
                ('county_name', models.TextField(blank=True, null=True)),
                ('county_weights', models.TextField(blank=True, null=True)),
                ('county_names_all', models.TextField(blank=True, null=True)),
                ('county_fips_all', models.TextField(blank=True, null=True)),
                ('imprecise', models.TextField(blank=True, null=True)),
                ('military', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'near_cars_uszip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('zip_code', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('description', models.TextField()),
                ('location_carry_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_carry_on', to='near_cars.location')),
                ('location_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pickup', to='near_cars.location')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('uuid', models.CharField(default=near_cars.utils.car_id_generator, max_length=5, primary_key=True, serialize=False)),
                ('carrying', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='near_cars.location')),
            ],
        ),
    ]
