# Generated by Django 4.2.1 on 2023-05-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('near_cars', '0002_alter_payload_location_carry_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='location_carry_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_carry_on', to='near_cars.location'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='location_pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pickup', to='near_cars.location'),
        ),
    ]
